### ISSUE TITLE
第二次从起硬盘安装时，卡在进度条最后一步

### ISSUE THREAD

**Issue by sakunoo** [zhongmax/XPS-9570-macOS#1]
安装 big sur的时候 第二次重启硬盘安装时，卡在进度条最后一步

但是用相同的EFI 安装catalina毫无问题

都是OC引导.折腾好久都不行，崩溃呀
小白太难了

**Comment by zhongmax** [comment]
强制关机，再开机试试，我之前安big sur也遇到进度条卡在那里不动，我强制关机，再开机，就可以了

**Comment by sakunoo** [comment]
好的，我得空去试一下，感谢回复
